{% set name = "detectron2" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9757fed05fa32acc2116ea038185f08409d5e854573e70f41909a358b70d1004

build:
  number: 0
  ? skip__###conda-selector###__win or pytorch == "1.9.*" and cuda_compiler_version == "11.0" or pytorch == "1.8.*" and cuda_compiler_version == "11.0" or pytorch == "1.7.*" and cuda_compiler_version != "10.2"
  : true
  script: {{ PYTHON }} -m pip install . -vv

  string: torch{{ pytorch | replace('.', '') | replace('*', '') }}_cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: torch{{ pytorch | replace('.', '') | replace('*', '') }}_cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}      # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    - pytorch-gpu {{ pytorch }}      # [cuda_compiler_version != "None"]
    - pytorch-cpu {{ pytorch }}      # [cuda_compiler_version == "None"]
  run:
    - {{ pin_compatible('pytorch-gpu', min_pin='x.x.x', max_pin='x.x') }}                  # [cuda_compiler_version != "None"]
    - {{ pin_compatible('pytorch-cpu', min_pin='x.x.x', max_pin='x.x') }}                  # [cuda_compiler_version == "None"]
    - python
    - cloudpickle
    - future
    - fvcore
    - matplotlib-base
    - pillow
    - pycocotools
    - pydot
    - tensorboard
    - termcolor >=1.1
    - tqdm >4.29.0
    - yacs >=0.1.6

test:
  imports:
    - detectron2
  requires:
    - black ==19.3b0
    - flake8
    - flake8-bugbear
    - flake8-comprehensions
    - isort

about:
  home: https://github.com/facebookresearch/detectron2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Detectron2 is FAIR's next-generation platform for object detection and segmentation.
  doc_url: https://github.com/facebookresearch/detectron2
  dev_url: https://github.com/facebookresearch/detectron2

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
